### ISSUE TITLE
Exports two desktop files, one without icon

### ISSUE THREAD

**Issue by wjt** [flathub/org.kde.marble#8]
This app exports two desktop files. They launch two different apps which are almost but not quite the same.

![Capture d’écran de 2021-04-28 16-21-46](https://user-images.githubusercontent.com/86760/116429491-d9792a00-a83d-11eb-84d3-bfffc777f13c.png)

![Capture d’écran de 2021-04-28 16-23-07](https://user-images.githubusercontent.com/86760/116429753-13e2c700-a83e-11eb-8b90-a06c26b95fe7.png)

## `org.kde.marble.desktop` 

This is labelled "KDE Marble", and has an icon.

## `org.kde.marble-qt.desktop`

This one is labelled "Marble" and has no icon. Perhaps this should just be deleted?

**Comment by tsdgeos** [comment]
yes the -qt one should be removed. @cho2 can you take care of it?

**Comment by cho2** [comment]
I'll take a look
